config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root "posts#index"

  resources :channels
  resources :posts do
    member do
      post 'like', to: 'posts#like'
      post 'dislike', to: 'posts#dislike'
    end
    resources :replies do
      post 'like', to: 'replies#like'
      post 'dislike', to: 'replies#dislike'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :posts
  has_many :users, through: :posts

  validates :title, presence: true
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Searchable
  acts_as_votable
  belongs_to :user
  belongs_to :channel
  has_many :replies, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

end

app/models/reply.rb
class Reply < ApplicationRecord
  acts_as_votable
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :channels, through: :posts

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  def name
    [firstname, lastname].select(&:present?).join(" ")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :index]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @channels = Channel.all.order('created_at desc')
    @posts = Post.all.preload(:user, :channel).order('created_at desc')
  end

  def show
    @channels = Channel.all.order('created_at desc')
    @posts = Post.preload(:user, :channel).where('channel_id = ?', @channel.id).page(params[:page])
  end

  def new
    @channel = Channel.new
  end

  def edit
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to root_path, notice: "Channel successfully created."
    else
      render :new
    end
  end

  def update
    if @channel.update(channel_params)
      redirect_to root_path, notice: "Channel successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @channel.destroy
    redirect_to root_path, notice: "Channel successfully destroyed."
  end

  private

  def set_channel
    @channel = Channel.find(params[:id]) if params.key?(:id)
  end

  def permitted_params
    [
      :title,
    ]
  end

  def channel_params
    params.fetch(:channel, {}).permit(permitted_params)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :update, :destroy, :like, :dislike]
  before_action :find_channels, only: [:index, :show, :new, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.preload(:user, :channel).order('created_at desc').page(params[:page])
  end

  def show
    @posts = Post.all.preload(:user, :channel).order('created_at desc').page(params[:page])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_path(@post), notice: "Post successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if current_user == @post.user
      if @post.update(post_params)
        redirect_to post_path(@post), notice: "Post successfully updated."
      else
        render :edit
      end
    else
      redirect_to post_path(@post), alert: "Your are not the post author."
    end
  end

  def destroy
    if current_user == @post.user
      @post.destroy
      redirect_to root_path, notice: "Post successfully destroyed."
    else
      redirect_to post_path(@post), alert: "Your are not the post author."
    end
  end

  def like
    @post.upvote_by current_user
    redirect_to post_path(@post), notice: "Upvote !"
  end

  def dislike
    @post.downvote_by current_user
    redirect_to post_path(@post), notice: "Downvote !"
  end

  private

  def set_post
    @post = Post.find(params[:id]) if params.key?(:id)
  end

  def permitted_params
    [
        :title,
        :content,
        :channel_id,
    ]
  end

  def post_params
    params.fetch(:post, {}).permit(permitted_params)
  end

  def find_channels
    @channels = Channel.all.order('created_at desc')
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reply, only: [:edit, :update, :destroy, :show, :like, :dislike]
  before_action :set_post, only: [:create, :edit, :show, :update, :destroy, :like, :dislike]

  def new
  end

  def create
    @reply = @post.replies.create(params[:reply].permit(:content, :post_id, :user_id))
    @reply.user_id = current_user.id

    if @reply.save
      redirect_to post_path(@post), notice: "Reply successfully created"
    else
      redirect_to post_path(@post), notice: "Reply did not save. Please try again."
    end

  end

  def edit
  end

  def update
    @reply = @post.replies.find(params[:id])

    if current_user == @reply.user
      if @reply.update(reply_params)
        redirect_to post_path(@post), notice: "Reply successfully updated."
      else
        render :edit
      end
    else
      redirect_to post_path(@post), alert: "Your are not the reply author."
    end
  end

  def show
  end

  def destroy
    @reply = @post.replies.find(params[:id])

    if current_user == @reply.user
      @reply.destroy
      redirect_to post_path(@post), notice: "Reply successfully destroyed."
    else
      redirect_to post_path(@post), alert: "Your are not the reply author."
    end
  end

  def like
    @reply = Reply.find(params[:reply_id])
    @reply.upvote_by current_user
    redirect_to post_path(@post), notice: "Upvote !"
  end

  def dislike
    @reply = Reply.find(params[:reply_id])
    @reply.downvote_by current_user
    redirect_to post_path(@post), notice: "Downvote !"
  end

  private

  def set_post
    @post = Post.find(params[:post_id]) if params.key?(:post_id)
  end

  def set_reply
    @reply = Reply.find(params[:id]) if params.key?(:id)
  end

  def permitted_params
    [
      :content,
    ]
  end

  def reply_params
    params.fetch(:reply, {}).permit(permitted_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon(id, style = "fa")
    id = id.to_s.tr("_", "-")
    content_tag(:span, class: "#{style} fa-#{id}") {}
  end

  def lf2br(str)
    str.to_s.gsub("\r", "").gsub("\n", "<br />").html_safe
  end

end

app/views/channels/_form.html.erb
<%= simple_form_for @channel do |f| %>
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-12"><%= f.input :title %></div>
      </div>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/channels/new.html.erb
<%= render 'form' %>

app/views/channels/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= render 'posts/sidebar' %>
  </div>
  <div class="col-sm-9">
    <%= render 'posts/list' %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div id="flash">
  <% flash.map do |type, messages| %>
    <% type = "success" if (type == "success" || type == "notice") %>
    <% type = "danger"  if (type == "warning" || type == "alert") %>

    <% messages = [messages] if messages.is_a?(String) %>
    <% messages.each do |message| %>
      <div class="alert alert-<%= type %> alert-dismissible alert-notify" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= lf2br message %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header id="header" class="nav navbar navbar-expand-lg fixed-top navbar-light border-bottom">
  <a class="navbar-brand" href="<%= main_app.root_path %>">
    <%= image_tag "logo.png", height: 50 %>
  </a>

  <button class="navbar-toggler" data-target="#nav" data-toggle="collapse">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div id="nav" class="collapse navbar-collapse">
    <% if current_user %>
      <%= render "layouts/user_nav" %>
    <% else %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link" href="<%= main_app.new_user_session_path %>">
            Login
          </a>
        </li>
      </ul>
    <% end %>
  </div>
</header>

app/views/layouts/_user_nav.html.erb
<ul class="navbar-nav ml-auto">
  <li class="nav-item dropdown">
    <a class="nav-link" href="#" data-toggle="dropdown">
      <%= icon(:user) %>
      <%= current_user.name %>
      <%= icon(:caret_down) %>
    </a>

    <div class="dropdown-menu">
      <a class="dropdown-item" href="<%= main_app.destroy_user_session_path %>" data-method="delete">
        <%= icon(:power_off) %>
        Logout
      </a>
    </div>
  </li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="turbolinks-cache-control" content="no-cache" />
  <title>HivebriteForum</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
</head>

<body
  data-controller="<%= params[:controller].parameterize %>"
  data-action="<%= params[:action].parameterize %>"
>
<%= render "layouts/header" %>

<main id="main">
  <%= render "layouts/flash" %>
  <%== yield %>
</main>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12"><%= f.input :title %></div>
      </div>
      <div class="row">
        <div class="col-md-12"><%= f.input :content %></div>
      </div>
      <div class="row">
        <div class="col-md-12"><%= f.association :channel, collection: @channels, prompt: "Select channel" %></div>
      </div>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Sujet</th>
    <th>Auteur</th>
    <th>Channel</th>
    <th>Réponse</th>
    <th>Date</th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%= post.user.name %></td>
      <td><%= post.channel.title %></td>
      <td><%= post.replies.count %></td>
      <td><%= post.created_at.strftime("%d/%m/%Y") %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @posts %>

app/views/posts/_sidebar.html.erb
<div>
  <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
  <%= link_to "New Channel", new_channel_path, class: 'btn btn-primary' %>
</div>
<br/>

<ul class="list-group">
  <% @channels.each do |c| %>
    <li class="list-group-item"><%= link_to c.title, c %></li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= render 'sidebar' %>
  </div>
  <div class="col-sm-9">
    <%= render 'list' %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= render 'sidebar' %>
  </div>
  <div class="col-sm-9">
    <div class="card">
      <div class="card-header">
        <h3><%= @post.title %></h3>
      </div>
      <div class="card-body">
        <h5 class="card-title">Post by <%= @post.user.name %> in <%= link_to @post.channel.title, @post.channel %></h5>
        <p class="card-text"><%= @post.content.html_safe %></p>
        <%= link_to "Like Post", like_post_path(@post), method: :post  %>
        <%= @post.get_upvotes.size %>
        <%= link_to "Dislike Post", dislike_post_path(@post), method: :post  %>
        <%= @post.get_downvotes.size %>
        <div>
          <br/>
          <%= link_to 'Edit Post', edit_post_path(@post), class:'btn btn-primary'%>
          <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Delete post?" }, class:' btn btn-primary' %>
        </div>
      </div>
    </div>
    <br/>
    <div id="post-replies">
      <%= render @post.replies %>
    </div>

    <hr />

    <h3>Leave a reply</h3>
    <% if user_signed_in? %>
      <%= render 'replies/form' %>
    <% else %>
      <p>To reply you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
        <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <% end %>
  </div>
</div>

app/views/replies/_form.html.erb
<%= simple_form_for([@post, @post.replies.build], remote: true) do |f| %>

  <div class="row">
    <div class="col col-sm-12"><%= f.input :content %></div>
  </div>

  <%= f.submit 'Leave a reply', class:'btn btn-primary' %>
<% end %>

app/views/replies/_reply.html.erb
<div class="card">
  <div class="card-body">
    <h6 class="card-text">Reply by <%= reply.user.name %> at <%= reply.created_at.strftime("%H:%M:%S") %></h6>
    <p class="card-text"><%= reply.content %></p>
    <%= link_to "Like Reply", post_reply_like_path(reply.post, reply), method: :post  %>
    <%= reply.get_upvotes.size %>
    <%= link_to "Dislike Reply", post_reply_dislike_path(reply.post, reply), method: :post  %>
    <%= reply.get_downvotes.size %>
    <div>
      <br/>
      <%= link_to 'Edit Reply', edit_post_reply_path(reply.post, reply), class:'btn btn-primary'%>
      <%= link_to 'Delete Reply', post_reply_path(reply.post, reply), method: :delete, data: { confirm: "Delete reply?" }, class:' btn btn-primary' %>
    </div>
  </div>
</div>

app/views/replies/create.js.erb
$("<%= escape_javascript(render(@reply)) %>").appendTo('#post-replies');

app/views/replies/edit.html.erb
<%= simple_form_for([@post, @reply]) do |f| %>

  <div class="row">
    <div class="col col-sm-12"><%= f.input :content %></div>
  </div>

  <%= f.submit 'Update reply', class:'btn btn-primary' %>
<% end %>